#
# Configuration for the crank api
server:
  port: 8510
crnk: 
  enabled: true
  domain-name: http://localhost:8510
  path-prefix: /api
  default-page-limit: 20
  max-page-limit: 1000
  allow-unknown-attributes: false
  return404-on-null: true
spring:
  datasource:
    url: jdbc:h2:~/ngfs;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa.hibernate.ddl-auto: create
  h2:
    console:
      enabled: true
