
# Create a new person
mutation PersonCreateMutation($pi: PersonInput) {
  createPerson(personInput: $pi) {
    id, givenName, surName
  }
}

#Update the person
mutation PersonUpdateMutation($pi: PersonInput) {
  updatePerson(personInput: $pi) {
    id, givenName, surName
  }
}

# Query people
query Query {
  people (orderBy:{field: "givenName", direction: "ASC"}) {
    id, givenName, surName
  }
}