#Add a new person
mutation PersonCreateMutation($pi: PersonInput) {
  createPerson(personInput: $pi) {
    id, givenName, surName
  }
}

# Update the Person
mutation PersonUpdateMutation($pi: PersonInput) {
  updatePerson(personInput: $pi) {
    id, givenName, surName
  }
}

#Sort by surname 
query QuerySortBySurName {
  people (orderBy:{field: "surName", direction: "ASC"}) {
    id, givenName, surName
  }
}

#Sort by given name
query QuerySortByGivenName {
  people (orderBy:{field: "givenName", direction: "DESC"}) {
    id, givenName, surName
  }
}

