#Sort by given name
query QueryPeople {
  people {
    id, givenName, surName
  }

}

query GetPersonQuery ($personId: String) {
person (personId: $personId)  {
  id, givenName, surName
  }
}
#Add a new person
mutation CreatePerson($newPerson: PersonInput) {
  createPerson(person: $newPerson) {
    id, givenName, surName
  }
}

#Update a person
mutation UpdatePerson ($updatePerson: PersonInput) {
  createPerson(person: $updatePerson) {
    id, givenName, surName
  }
}

subscription SubscribeToPersonChanged ($personId: UUID) {
  personChanged(id: $personId) {
     id, givenName, surName
  }
}
