#
# Configuration for the crank api
server:
  port: 8510
crnk: 
  enabled: true
  domain-name: http://localhost:8510
  path-prefix: /api
  default-page-limit: 20
  max-page-limit: 1000
  allow-unknown-attributes: false
  return404-on-null: true