#
# Configuration for the crank api
crnk: 
  enabled: true
  domain-name: http://localhost:8080
  path-prefix: /api
  default-page-limit: 20
  max-page-limit: 1000
  allow-unknown-attributes: false
  return404-on-null: true